### ISSUE TITLE
Error: <urlopen error Remote end closed connection without response>

### ISSUE THREAD

**Issue by huameiwei-vc** [agoulddesign/krita-bg-remove-bria#1]
I turned on the clash proxy and it still doesn't work!

**Comment by agoulddesign** [comment]
Can you please verify that you can communicate with the address: "engine.prod.bria-api.com". Either by opening in a browser or by pinging?

Please provide version of Krita and operating system version, as well as any information on your internet connection setup (ip/ifconfig data?)

**Comment by agoulddesign** [comment]
Also please verify your firewall isn't blocking Krita (try temporarily disabling it to see if this resolves the issue).

Here is a simple ping script you can run in the _Krita Scripter_ to see if you can contact the remote server within Krita itself:

```
import socket
import time

def simple_ping(host, count=4):
    print(f"Pinging {host}...")
    for i in range(count):
        try:
            start_time = time.time()
            # Create a socket object
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            # Set a timeout for the connection attempt
            sock.settimeout(2)
            # Attempt to connect
            result = sock.connect_ex((host, 80))
            end_time = time.time()
            
            if result == 0:
                print(f"Ping successful: {host} - Time: {(end_time - start_time)*1000:.2f}ms")
            else:
                print(f"Ping failed: {host} - Host is not responding")
            
            # Close the socket
            sock.close()
        except socket.gaierror:
            print(f"Ping error: {host} - Hostname could not be resolved")
        except socket.error:
            print(f"Ping error: {host} - Couldn't connect to server")
        
        # Wait a second before the next ping
        time.sleep(1)

# Example usage
simple_ping('engine.prod.bria-api.com')
```

**Comment by huameiwei-vc** [comment]
Thank you very much for your reply!
The web page can be opened at engine.prod.bria-api.com, and ping works too. Scripts also work.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/3b3f5f1f-417d-46d3-8ac5-bdf1da50aeb0">
The krita version is:
<img width="573" alt="image" src="https://github.com/user-attachments/assets/cd46cea3-8d81-4d5a-8fd3-7084e58c0cce">
But the result still cannot be used，I've shut down the firewall, too.
<img width="959" alt="image" src="https://github.com/user-attachments/assets/326aae3d-a296-4df2-ab7b-22e7e129e2d3">

**Comment by agoulddesign** [comment]
Thank you for the info.

Updated my Krita to 5.2.3 (was on 5.2.2) and had no issues with that.

I assume you had no issue getting an API token from Bria, so it's not likely a region issue, but if you could log in to the Bria.ai website and verify you can use other tools at [labs.bria.ai](https://labs.bria.ai/) (upload an image to customize), that would verify you can access the tools from your location.

It appears you're using OSX (Mac), so I will look at possible conflicts there. I will likely have to spin up a virtual environment to test, so it may take a bit of time.

**Comment by huameiwei-vc** [comment]
Thank you very much. I do need this tool if you have time to test it!

**Comment by agoulddesign** [comment]
Added a new release with some fixes that I think may help (didn't test it in MacOS yet, busy with the Crowdstrike fiasco).

Please note that I renamed the extension/directory so you will need to remove the plugin before installing the new one (~/Library/Application Support/krita/pykrita/background_remover and background_remover.desktop).

Let me know if this resolved the issue. If not, I will do some further investigation and testing.

**Comment by huameiwei-vc** [comment]
I deleted the original plugin and reinstalled it from fresh and still have the original error.

**Comment by agoulddesign** [comment]
Added a new release. Verified that it works on MacOS. Please let me know if you have any further issues, and enjoy!

Thank you so much for your help.
